services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    ports:
      - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    labels:
      - "io.containers.autoupdate=registry"
    environment:
      - SCARF_NO_ANALYTICS=true
      - DO_NOT_TRACK=true
      - ANONYMIZED_TELEMETRY=false
      - WEBUI_AUTH=False
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - OPENAI_API_BASE_URL=http://host.containers.internal:8080/v1
    volumes:
      - ${HOME}/.local/share/open-webui/data:/app/backend/data:U
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
